name: extended_yaml
description: YAML parser with extra non-standard features
version: 0.4.1
repository: https://github.com/dbck-gsc/extended_yaml

environment:
  sdk: ^3.7.0

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
