name: extended_yaml
description: YAML parser with extended features, such as merging maps and including external files
version: 0.5.0
repository: https://github.com/dbck-gsc/extended_yaml

environment:
  sdk: ^3.7.0

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  lints: ^5.1.1
  mocktail: ^1.0.0
  test: ^1.16.0
